# Parameters for apriltags preprocessing
fast_enabled: 1
fast_period: 0.5
fast_v_crop: 175
fast_v_off:  -130
fast_h_off:  0
fast_h_crop: 0
fast_x_down:  1.0
global_enabled: 0
global_period: 0.3
global_v_off:   -115
global_h_off:   0
global_v_crop:  150
global_h_crop:  0
global_x_down:  1
